/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIocsRouteImport } from './routes/_authenticated/iocs'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as ApiPublicSensorIngestRouteImport } from './routes/api/public/sensor/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIocsRoute = AuthenticatedIocsRouteImport.update({
  id: '/iocs',
  path: '/iocs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSensorIngestRoute = ApiPublicSensorIngestRouteImport.update({
  id: '/api/public/sensor/ingest',
  path: '/api/public/sensor/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/iocs': typeof AuthenticatedIocsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/api/public/sensor/ingest': typeof ApiPublicSensorIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/iocs': typeof AuthenticatedIocsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/api/public/sensor/ingest': typeof ApiPublicSensorIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/iocs': typeof AuthenticatedIocsRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/api/public/sensor/ingest': typeof ApiPublicSensorIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/dashboard'
    | '/iocs'
    | '/personas'
    | '/sensors'
    | '/sessions/$id'
    | '/api/public/sensor/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/dashboard'
    | '/iocs'
    | '/personas'
    | '/sensors'
    | '/sessions/$id'
    | '/api/public/sensor/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/_authenticated/iocs'
    | '/_authenticated/personas'
    | '/_authenticated/sensors'
    | '/_authenticated/sessions/$id'
    | '/api/public/sensor/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSensorIngestRoute: typeof ApiPublicSensorIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iocs': {
      id: '/_authenticated/iocs'
      path: '/iocs'
      fullPath: '/iocs'
      preLoaderRoute: typeof AuthenticatedIocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sensor/ingest': {
      id: '/api/public/sensor/ingest'
      path: '/api/public/sensor/ingest'
      fullPath: '/api/public/sensor/ingest'
      preLoaderRoute: typeof ApiPublicSensorIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIocsRoute: typeof AuthenticatedIocsRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIocsRoute: AuthenticatedIocsRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSensorIngestRoute: ApiPublicSensorIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
